/* 
 * Employees
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MISA.OAS.OpenApi.SDK.Api;
using MISA.OAS.OpenApi.SDK.Model;
using MISA.OAS.OpenApi.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace MISA.OAS.OpenApi.SDK.Test
{
    /// <summary>
    ///  Class for testing Employee
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EmployeeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Employee
        //private Employee instance;

        public EmployeeTests()
        {
            // TODO uncomment below to create an instance of Employee
            //instance = new Employee();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Employee
        /// </summary>
        [Fact]
        public void EmployeeInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Employee
            //Assert.IsInstanceOfType<Employee> (instance, "variable 'instance' is a Employee");
        }


        /// <summary>
        /// Test the property 'EmployeeId'
        /// </summary>
        [Fact]
        public void EmployeeIdTest()
        {
            // TODO unit test for the property 'EmployeeId'
        }
        /// <summary>
        /// Test the property 'EmployeeCode'
        /// </summary>
        [Fact]
        public void EmployeeCodeTest()
        {
            // TODO unit test for the property 'EmployeeCode'
        }
        /// <summary>
        /// Test the property 'EmployeeName'
        /// </summary>
        [Fact]
        public void EmployeeNameTest()
        {
            // TODO unit test for the property 'EmployeeName'
        }
        /// <summary>
        /// Test the property 'Gender'
        /// </summary>
        [Fact]
        public void GenderTest()
        {
            // TODO unit test for the property 'Gender'
        }

    }

}
