/* 
 * Employees
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MISA.OAS.OpenApi.SDK.Api;
using MISA.OAS.OpenApi.SDK.Model;
using MISA.OAS.OpenApi.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace MISA.OAS.OpenApi.SDK.Test
{
    /// <summary>
    ///  Class for testing ResponseResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ResponseResultTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ResponseResult
        //private ResponseResult instance;

        public ResponseResultTests()
        {
            // TODO uncomment below to create an instance of ResponseResult
            //instance = new ResponseResult();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ResponseResult
        /// </summary>
        [Fact]
        public void ResponseResultInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ResponseResult
            //Assert.IsInstanceOfType<ResponseResult> (instance, "variable 'instance' is a ResponseResult");
        }


        /// <summary>
        /// Test the property 'ResultMessage'
        /// </summary>
        [Fact]
        public void ResultMessageTest()
        {
            // TODO unit test for the property 'ResultMessage'
        }
        /// <summary>
        /// Test the property 'ResultStream'
        /// </summary>
        [Fact]
        public void ResultStreamTest()
        {
            // TODO unit test for the property 'ResultStream'
        }

    }

}
