/*
 * Employees
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;
using Microsoft.AspNetCore.Authorization;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using MISA.OAS.Finance.Service.Attributes;
using MISA.OAS.Finance.Service.Models;

namespace MISA.OAS.Finance.Service.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class DefaultApiController : ControllerBase
    { 
        /// <summary>
        /// xóa nhân viên
        /// </summary>
        /// <param name="userID">ID người dùng</param>
        /// <response code="200">Xóa nhân viên.</response>
        /// <response code="400">Bad Request</response>
        /// <response code="500">Internal Server Error</response>
        [HttpDelete]
        [Route("/employees")]
        [ValidateModelState]
        [SwaggerOperation("EmployeesDelete")]
        [SwaggerResponse(statusCode: 200, type: typeof(ResponseResult), description: "Xóa nhân viên.")]
        [SwaggerResponse(statusCode: 400, type: typeof(Error), description: "Bad Request")]
        [SwaggerResponse(statusCode: 500, type: typeof(Error), description: "Internal Server Error")]
        public virtual IActionResult EmployeesDelete([FromQuery][Required()]Guid userID)
        { 

            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(ResponseResult));
            //TODO: Uncomment the next line to return response 400 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(400, default(Error));
            //TODO: Uncomment the next line to return response 500 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(500, default(Error));
            string exampleJson = null;
            exampleJson = "{\r\n  \"DateOfBirth\" : \"2000-01-23\",\r\n  \"Salary\" : 6.027456183070403,\r\n  \"Email\" : \"Email\",\r\n  \"EmployeeCode\" : \"EmployeeCode\",\r\n  \"PositionName\" : \"PositionName\",\r\n  \"PositionId\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\",\r\n  \"IdentityPlace\" : \"IdentityPlace\",\r\n  \"Gender\" : 0,\r\n  \"TaxCode\" : \"TaxCode\",\r\n  \"WorkStatus\" : 1,\r\n  \"PhoneNumber\" : \"PhoneNumber\",\r\n  \"DepartmentName\" : \"DepartmentName\",\r\n  \"DepartmentId\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\",\r\n  \"EmployeeId\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\",\r\n  \"EmployeeName\" : \"EmployeeName\",\r\n  \"IdentityDate\" : \"2000-01-23\",\r\n  \"JoinDate\" : \"2000-01-23\",\r\n  \"IdentityNumber\" : \"IdentityNumber\"\r\n}";
            
            var example = exampleJson != null
            ? JsonConvert.DeserializeObject<ResponseResult>(exampleJson)
            : default(ResponseResult);
            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        /// thêm nhân viên
        /// </summary>
        /// <param name="responseResult"></param>
        /// <response code="201">thêm thành công.</response>
        /// <response code="400">Bad Request</response>
        /// <response code="500">Internal Server Error</response>
        [HttpPost]
        [Route("/employees")]
        [ValidateModelState]
        [SwaggerOperation("EmployeesPost")]
        [SwaggerResponse(statusCode: 201, type: typeof(ResponseResult), description: "thêm thành công.")]
        [SwaggerResponse(statusCode: 400, type: typeof(Error), description: "Bad Request")]
        [SwaggerResponse(statusCode: 500, type: typeof(Error), description: "Internal Server Error")]
        public virtual IActionResult EmployeesPost([FromBody]ResponseResult responseResult)
        { 

            //TODO: Uncomment the next line to return response 201 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(201, default(ResponseResult));
            //TODO: Uncomment the next line to return response 400 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(400, default(Error));
            //TODO: Uncomment the next line to return response 500 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(500, default(Error));
            string exampleJson = null;
            exampleJson = "{\r\n  \"DateOfBirth\" : \"2000-01-23\",\r\n  \"Salary\" : 6.027456183070403,\r\n  \"Email\" : \"Email\",\r\n  \"EmployeeCode\" : \"EmployeeCode\",\r\n  \"PositionName\" : \"PositionName\",\r\n  \"PositionId\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\",\r\n  \"IdentityPlace\" : \"IdentityPlace\",\r\n  \"Gender\" : 0,\r\n  \"TaxCode\" : \"TaxCode\",\r\n  \"WorkStatus\" : 1,\r\n  \"PhoneNumber\" : \"PhoneNumber\",\r\n  \"DepartmentName\" : \"DepartmentName\",\r\n  \"DepartmentId\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\",\r\n  \"EmployeeId\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\",\r\n  \"EmployeeName\" : \"EmployeeName\",\r\n  \"IdentityDate\" : \"2000-01-23\",\r\n  \"JoinDate\" : \"2000-01-23\",\r\n  \"IdentityNumber\" : \"IdentityNumber\"\r\n}";
            
            var example = exampleJson != null
            ? JsonConvert.DeserializeObject<ResponseResult>(exampleJson)
            : default(ResponseResult);
            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        /// sửa nhân viên
        /// </summary>
        /// <param name="employeeId">ID người dùng</param>
        /// <param name="responseResult"></param>
        /// <response code="200">cập nhật thành công.</response>
        /// <response code="400">Bad Request</response>
        /// <response code="500">Internal Server Error</response>
        [HttpPut]
        [Route("/employees")]
        [ValidateModelState]
        [SwaggerOperation("EmployeesPut")]
        [SwaggerResponse(statusCode: 200, type: typeof(ResponseResult), description: "cập nhật thành công.")]
        [SwaggerResponse(statusCode: 400, type: typeof(Error), description: "Bad Request")]
        [SwaggerResponse(statusCode: 500, type: typeof(Error), description: "Internal Server Error")]
        public virtual IActionResult EmployeesPut([FromQuery][Required()]Guid employeeId, [FromBody]ResponseResult responseResult)
        { 

            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(ResponseResult));
            //TODO: Uncomment the next line to return response 400 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(400, default(Error));
            //TODO: Uncomment the next line to return response 500 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(500, default(Error));
            string exampleJson = null;
            exampleJson = "{\r\n  \"DateOfBirth\" : \"2000-01-23\",\r\n  \"Salary\" : 6.027456183070403,\r\n  \"Email\" : \"Email\",\r\n  \"EmployeeCode\" : \"EmployeeCode\",\r\n  \"PositionName\" : \"PositionName\",\r\n  \"PositionId\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\",\r\n  \"IdentityPlace\" : \"IdentityPlace\",\r\n  \"Gender\" : 0,\r\n  \"TaxCode\" : \"TaxCode\",\r\n  \"WorkStatus\" : 1,\r\n  \"PhoneNumber\" : \"PhoneNumber\",\r\n  \"DepartmentName\" : \"DepartmentName\",\r\n  \"DepartmentId\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\",\r\n  \"EmployeeId\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\",\r\n  \"EmployeeName\" : \"EmployeeName\",\r\n  \"IdentityDate\" : \"2000-01-23\",\r\n  \"JoinDate\" : \"2000-01-23\",\r\n  \"IdentityNumber\" : \"IdentityNumber\"\r\n}";
            
            var example = exampleJson != null
            ? JsonConvert.DeserializeObject<ResponseResult>(exampleJson)
            : default(ResponseResult);
            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        /// lấy danh sách nhân viên
        /// </summary>
        /// <response code="200">trả dữu liệu thành công</response>
        /// <response code="400">Bad Request</response>
        /// <response code="500">Internal Server Error</response>
        [HttpGet]
        [Route("/employees")]
        [ValidateModelState]
        [SwaggerOperation("GetEmployees")]
        [SwaggerResponse(statusCode: 200, type: typeof(ResponseResult), description: "trả dữu liệu thành công")]
        [SwaggerResponse(statusCode: 400, type: typeof(Error), description: "Bad Request")]
        [SwaggerResponse(statusCode: 500, type: typeof(Error), description: "Internal Server Error")]
        public virtual IActionResult GetEmployees()
        { 

            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(ResponseResult));
            //TODO: Uncomment the next line to return response 400 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(400, default(Error));
            //TODO: Uncomment the next line to return response 500 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(500, default(Error));
            string exampleJson = null;
            exampleJson = "{\r\n  \"DateOfBirth\" : \"2000-01-23\",\r\n  \"Salary\" : 6.027456183070403,\r\n  \"Email\" : \"Email\",\r\n  \"EmployeeCode\" : \"EmployeeCode\",\r\n  \"PositionName\" : \"PositionName\",\r\n  \"PositionId\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\",\r\n  \"IdentityPlace\" : \"IdentityPlace\",\r\n  \"Gender\" : 0,\r\n  \"TaxCode\" : \"TaxCode\",\r\n  \"WorkStatus\" : 1,\r\n  \"PhoneNumber\" : \"PhoneNumber\",\r\n  \"DepartmentName\" : \"DepartmentName\",\r\n  \"DepartmentId\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\",\r\n  \"EmployeeId\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\",\r\n  \"EmployeeName\" : \"EmployeeName\",\r\n  \"IdentityDate\" : \"2000-01-23\",\r\n  \"JoinDate\" : \"2000-01-23\",\r\n  \"IdentityNumber\" : \"IdentityNumber\"\r\n}";
            
            var example = exampleJson != null
            ? JsonConvert.DeserializeObject<ResponseResult>(exampleJson)
            : default(ResponseResult);
            //TODO: Change the data returned
            return Ok(example);
        }
    }
}
