/* 
 * UserApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using MISA.OAS.Finance.SDK.Client;
using MISA.OAS.Finance.SDK.Model;

namespace MISA.OAS.Finance.SDK.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IUsersApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// lấy danh sách tất cả người dùng
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="MISA.OAS.Finance.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>List&lt;User&gt;</returns>
        List<User> UsersGet ();

        /// <summary>
        /// lấy danh sách tất cả người dùng
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="MISA.OAS.Finance.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of List&lt;User&gt;</returns>
        ApiResponse<List<User>> UsersGetWithHttpInfo ();
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IUsersApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// lấy danh sách tất cả người dùng
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="MISA.OAS.Finance.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of List&lt;User&gt;</returns>
        System.Threading.Tasks.Task<List<User>> UsersGetAsync ();

        /// <summary>
        /// lấy danh sách tất cả người dùng
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="MISA.OAS.Finance.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (List&lt;User&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<User>>> UsersGetAsyncWithHttpInfo ();
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IUsersApi : IUsersApiSync, IUsersApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class UsersApi : IUsersApi
    {
        private MISA.OAS.Finance.SDK.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="UsersApi"/> class.
        /// </summary>
        /// <returns></returns>
        public UsersApi() : this((string) null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="UsersApi"/> class.
        /// </summary>
        /// <returns></returns>
        public UsersApi(String basePath)
        {
            this.Configuration = MISA.OAS.Finance.SDK.Client.Configuration.MergeConfigurations(
                MISA.OAS.Finance.SDK.Client.GlobalConfiguration.Instance,
                new MISA.OAS.Finance.SDK.Client.Configuration { BasePath = basePath }
            );
            this.Client = new MISA.OAS.Finance.SDK.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new MISA.OAS.Finance.SDK.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = MISA.OAS.Finance.SDK.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="UsersApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public UsersApi(MISA.OAS.Finance.SDK.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = MISA.OAS.Finance.SDK.Client.Configuration.MergeConfigurations(
                MISA.OAS.Finance.SDK.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new MISA.OAS.Finance.SDK.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new MISA.OAS.Finance.SDK.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = MISA.OAS.Finance.SDK.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="UsersApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public UsersApi(MISA.OAS.Finance.SDK.Client.ISynchronousClient client,MISA.OAS.Finance.SDK.Client.IAsynchronousClient asyncClient, MISA.OAS.Finance.SDK.Client.IReadableConfiguration configuration)
        {
            if(client == null) throw new ArgumentNullException("client");
            if(asyncClient == null) throw new ArgumentNullException("asyncClient");
            if(configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = MISA.OAS.Finance.SDK.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public MISA.OAS.Finance.SDK.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public MISA.OAS.Finance.SDK.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public MISA.OAS.Finance.SDK.Client.IReadableConfiguration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public MISA.OAS.Finance.SDK.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// lấy danh sách tất cả người dùng 
        /// </summary>
        /// <exception cref="MISA.OAS.Finance.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>List&lt;User&gt;</returns>
        public List<User> UsersGet ()
        {
             MISA.OAS.Finance.SDK.Client.ApiResponse<List<User>> localVarResponse = UsersGetWithHttpInfo();
             return localVarResponse.Data;
        }

        /// <summary>
        /// lấy danh sách tất cả người dùng 
        /// </summary>
        /// <exception cref="MISA.OAS.Finance.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of List&lt;User&gt;</returns>
        public MISA.OAS.Finance.SDK.Client.ApiResponse< List<User> > UsersGetWithHttpInfo ()
        {
            MISA.OAS.Finance.SDK.Client.RequestOptions localVarRequestOptions = new MISA.OAS.Finance.SDK.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };

            var localVarContentType = MISA.OAS.Finance.SDK.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = MISA.OAS.Finance.SDK.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);



            // make the HTTP request
            var localVarResponse = this.Client.Get< List<User> >("/users", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("UsersGet", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// lấy danh sách tất cả người dùng 
        /// </summary>
        /// <exception cref="MISA.OAS.Finance.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of List&lt;User&gt;</returns>
        public async System.Threading.Tasks.Task<List<User>> UsersGetAsync ()
        {
             MISA.OAS.Finance.SDK.Client.ApiResponse<List<User>> localVarResponse = await UsersGetAsyncWithHttpInfo();
             return localVarResponse.Data;

        }

        /// <summary>
        /// lấy danh sách tất cả người dùng 
        /// </summary>
        /// <exception cref="MISA.OAS.Finance.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (List&lt;User&gt;)</returns>
        public async System.Threading.Tasks.Task<MISA.OAS.Finance.SDK.Client.ApiResponse<List<User>>> UsersGetAsyncWithHttpInfo ()
        {

            MISA.OAS.Finance.SDK.Client.RequestOptions localVarRequestOptions = new MISA.OAS.Finance.SDK.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };
            
            foreach (var _contentType in _contentTypes)
                localVarRequestOptions.HeaderParameters.Add("Content-Type", _contentType);
            
            foreach (var _accept in _accepts)
                localVarRequestOptions.HeaderParameters.Add("Accept", _accept);
            


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<List<User>>("/users", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("UsersGet", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
