#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster AS build
WORKDIR /src
COPY ["MISA.MintaxUI/MISA.MintaxUI.csproj", "MISA.MintaxUI/"]
RUN dotnet restore "MISA.MintaxUI/MISA.MintaxUI.csproj"
COPY . .
WORKDIR "/src/MISA.MintaxUI"
RUN dotnet build "MISA.MintaxUI.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "MISA.MintaxUI.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "MISA.MintaxUI.dll"]

# Build Vue SPA App
FROM node:latest as build-stage
WORKDIR /app
COPY MISA.MintaxUI/wwwroot/package*.json ./
RUN npm install
ADD ./MISA.MintaxUI/wwwroot ./
RUN npm run build-dev

FROM nginx as production-stage
WORKDIR /app
COPY --from=build-stage /app/dist /app
COPY /MISA.MintaxUI/wwwroot/nginx.conf /etc/nginx/nginx.conf
