node('Centos-Mintax') {
    def app
    stage('Check SCM') {
        checkout scm
    }
    dir('MISA.Mintax'){
    stage('Build image') {
        app = docker.build("misadockerhub.vn:30100/mintax-web:${env.BUILD_NUMBER}","-f ./MISA.MintaxUI/Dockerfile .")
    }
    }
    stage('Test image') {
        sh 'echo "Test123123123"'
    }
    
    stage('Push image') {
        docker.withRegistry(''){
            app.push()
        }
    }
    dir('MISA.Mintax/helmtest/mintax-web'){
    stage('Deploy to helm') {
       sh 'pwd'
       sh """
         echo "Build number in sh script: ${env.BUILD_NUMBER}"
         helm upgrade mintax-web mintax/mintax-web --set image.tag=${env.BUILD_NUMBER} --namespace=mintax-test
       """
    	}
   
    }
    stage('Slack send notified'){
        slackSend channel: 'testnotifi', message: "Success deploy mintax-web ${env.BUILD_NUMBER}"
    }
}
