openapi: '3.0.0'
description: 'Định nghĩa các responses dùng chung'
info:
  title: 'responses common'
  version: '1.0'
tags:
  - Common
paths: {}
components:
  responses:
    '400':
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: 'error.v1.yaml'
          examples:
            400ReturnInvalidInput:       
              $ref: 'examples/response400.v1.yaml#/components/examples/400ReturnInvalidInput'
            400ReturnInvalidInputValidationNull:
              $ref: 'examples/response400.v1.yaml#/components/examples/400ReturnInvalidInputValidationNull'
    '500':
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: 'error.v1.yaml'
          examples:
            500ReturnException:       
                $ref: 'examples/response500.v1.yaml#/components/examples/500ReturnException'
