/*
 * UserApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;
using Microsoft.AspNetCore.Authorization;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using MISA.OAS.Finance.Service.Attributes;
using MISA.OAS.Finance.Service.Models;

namespace MISA.OAS.Finance.Service.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class UsersApiController : ControllerBase
    { 
        /// <summary>
        /// lấy danh sách tất cả người dùng
        /// </summary>
        /// <response code="200">mảng danh sách người dùng</response>
        /// <response code="400">Bad request</response>
        /// <response code="500">Internal Server Error</response>
        /// <response code="0">unexpected error</response>
        [HttpGet]
        [Route("/v2/users")]
        [ValidateModelState]
        [SwaggerOperation("UsersGet")]
        [SwaggerResponse(statusCode: 200, type: typeof(List<User>), description: "mảng danh sách người dùng")]
        [SwaggerResponse(statusCode: 400, type: typeof(Error1), description: "Bad request")]
        [SwaggerResponse(statusCode: 500, type: typeof(Error1), description: "Internal Server Error")]
        [SwaggerResponse(statusCode: 0, type: typeof(Error1), description: "unexpected error")]
        public virtual IActionResult UsersGet()
        { 

            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(List<User>));
            //TODO: Uncomment the next line to return response 400 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(400, default(Error1));
            //TODO: Uncomment the next line to return response 500 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(500, default(Error1));
            //TODO: Uncomment the next line to return response 0 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(0, default(Error1));
            string exampleJson = null;
            exampleJson = "{\r\n  \"UserName\" : \"UserName\",\r\n  \"UserId\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\",\r\n  \"UserAddress\" : \"UserAddress\",\r\n  \"UserDateOfBirth\" : \"2000-01-23\"\r\n}";
            
            var example = exampleJson != null
            ? JsonConvert.DeserializeObject<List<User>>(exampleJson)
            : default(List<User>);
            //TODO: Change the data returned
            return new ObjectResult(example);
        }
    }
}
