/* 
 * UserApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MISA.OAS.Finance.Service.Api;
using MISA.OAS.Finance.Service.Model;
using MISA.OAS.Finance.Service.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace MISA.OAS.Finance.Service.Test
{
    /// <summary>
    ///  Class for testing Error1
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class Error1Tests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Error1
        //private Error1 instance;

        public Error1Tests()
        {
            // TODO uncomment below to create an instance of Error1
            //instance = new Error1();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Error1
        /// </summary>
        [Fact]
        public void Error1InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Error1
            //Assert.IsInstanceOfType<Error1> (instance, "variable 'instance' is a Error1");
        }


        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Fact]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }
        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }

    }

}
